modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="biomes_galore"
version="1.0.0"
displayName="Biomes Galore!"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="kgree, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.biomes_galore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration